### ISSUE TITLE
Naming issues, restoring old names

### ISSUE THREAD

**Issue by maartenbreddels** [bqplot/bqscales#62]
I think we should be careful not to break other libraries, and not rename things. 
e.g. `computeAndSetDomain` was originally `compute_and_set_domain` which now means that bqplot-image-gl will not work with bqscales. Even though I can use the new name, that means the newer versions of bqplot-image-gl will not work with old versions of bqplot and vice versa.

If we really want to have new names, we should have an alias, but even then, if a new library uses that new name, it will never work with older versions.

What do you think, should we simply restore the old names?

**Comment by martinRenou** [comment]
I think it's a good opportunity for renaming while we are making a backward incompatible release.

Though we should probably make a deprecation warning pass indeed, and actually rename those APIs in the next backward incompatible release.

**Comment by maartenbreddels** [comment]
I think we should avoid any backward-incompatible change. We can of course change the semver version number, and say it has changed in an incompatible way, but the pain and suffering from having to pin versions and not being able to create environments with a mix of a few libraries do do pinning (especially max versions numbers) are large.

If we keep the old names forever, we do no harm, and all our users will be happy. We just have to accept (as developers) that we have to stare at those ugly naming conventions for years to come:)

**Comment by martinRenou** [comment]
I don't think we should be afraid of making backward incompatible changes, that's why major versions are there. We sometimes need to move on from old decisions.

There is a sane middle ground to find between the "no backward incompatible change" policy and the "backward incompatible changes on minor updates because I don't like semver and I don't care" policy...

**Comment by martinRenou** [comment]
But I totally agree we could ease that by keeping the old names around for some time, adding a deprecation warning .

**Comment by maartenbreddels** [comment]
There are necessary breaking changes, because of wrong functionality etc, and there is unneeded breaking changes. As well as, even though there might be a breaking change release, if a library only uses a subset of the API, it might avoid breakage.

And this happens a lot in practice, most libraries are compatible with a series of major version releases, because they don't depend on the breaking parts. Same here. We could keep this part non breaking.

**Comment by maartenbreddels** [comment]
> But I totally agree we could ease that by keeping the old names around for some time, adding a deprecation warning .

Lets see if typescript has some magic for that?

**Comment by martinRenou** [comment]
> Lets see if typescript has some magic for that?

I recall seeing some things like that in JupyterLab's codebase. Adding a `@deprecated` in the "docstring" https://github.com/jupyterlab/jupyterlab/blob/72accc92be2a9d3f191d15f42e31a1b2eb3a260d/packages/ui-components/src/components/menu.ts#L113. Idk if that's TypeScript related though?
